language: java
sudo: false
install:
- "./gradlew clean classes testClasses -x test"
jdk:
- oraclejdk8
before_install:
- "./gradlew --version"
addons:
  sonarqube:
    token:
      secure: TNfo/oMaZLC9KDxdVB+WfCkNKiOi0hBHZWBMlJCwq2A2OYnWhHBjP8yOU8BDmZNlknjdSouV9eWKvU47oi+E2XUEcy41aBAkyZX06YYZYM7dsAjot5qPKY8O0zjp/62EhsggyD3kC02qNdFdHFfonqB33uMELePjWUimGv3Ctlb5V3ukqwU9UuODBE/yt9a0d5LXtaUxsFJdTym7j77patLaQU/CnL75X/VTpr427xAD/OVtWtgQzIlmhQnaA43xdNcDFTZRHL16OP17sjQrO/fo7lMcG7Kx9uJIsqFpHh5XGDmC9Hp6tECewkxOwFHjmYg/E1uviUt5NFtVHcokkc6IMIjKnOMC+aJ0PwXO5nibKTrIMJKMm1MYZq/yaaOxYdaA+gfndmmIP2dDhK7hup0XfBg56xYaGrp2Em3+QZGRk5OAEnT3lPWRy97g0uA4rplMt2MJldcM3+d/LlIjhszCzs1p8oYgE8HPrPYBx0Kp8Yrnq8b0Wn0YDguChImtnqarSb9W79o3BVR299GqVhyQ2H+2EvJOtDvYmb3J3ohf0HBLn087jy7PozxKPq3BNJGeQw8I2q1f82sJOx2YR/jHXdsfHmxcrGDaVqJ+XLD8Ncn7LcJ/yiuCzXniviT5dqLvw9h5bsB0urTP1Zz6zRSxzya36fAWqmAqpb2uqk4=
script:
- "./gradlew test jacocoTestReport sonarqube"
after_success:
- bash <(curl -s https://codecov.io/bash)
os:
- linux
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"