name: Process Runner, a java based process and script runner.
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
timezone: America/New_York
google_analytics: UA-47766602-3
exclude: README.md